name: Test, build and push 

on: [push, pull_request]

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo 
        uses: actions/checkout@v4

      - name: Configurar python
        uses: actions/setup-python@v5

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar pruebas
        run: pytest tests/ -v --tb=short --junitxml=report.xml

      - name: Subir reporte de pruebas
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report.xml






          
